name: Publish to JSR

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:
    inputs:
      ref:
        description: Git revision to publish
        required: true
        default: main

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref || github.ref }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno task default
      - run: git restore -- .idea/modules.xml .idea/vcs.xml
      - run: deno publish
